services:
  db:
    image: postgres:16-alpine
    container_name: livraria-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin123}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-livraria1212}
      POSTGRES_DB: ${POSTGRES_DB:-livraria}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin123} -d ${POSTGRES_DB:-livraria}"]
      interval: 10s
      timeout: 3s
      retries: 10
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - app-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livraria-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-livraria}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-admin123}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-livraria1212}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge
